version: '3.8'

services:
  front:
    container_name: hayabusatrip-frontend
    env_file:
      - ./.env.local
    build: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/frontend
      - /frontend/node_modules
    command: yarn dev
    # 本番用
    # command: yarn build && yarn start
